spring.application.name=app

# Banco em memoria para desenvolvimento (trocar para MySQL em producao)
spring.datasource.url=jdbc:h2:mem:matriculas
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
